### ISSUE TITLE
Assumes confluence is behind SSL

### ISSUE THREAD

**Issue by magnayn** [amwelch-oss/hubot-confluence#13]

**Comment by amwelch** [comment]
Hi, thanks for reporting this.
I will add a configuration flag to support http as well.

**Comment by amwelch** [comment]
The environment variable HUBOT_CONFLUENCE_PROTOCOL is now supported. It defaults to http, but  you can set it to http to make requests to Confluence without using SSL.

Please let me know if you have any additional issues or feature requests.
