### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by Anirudh-Banarji** [amwelch-oss/hubot-confluence#4]
Getting the following error when I used the command : @botname confluence search XXX

I have set HUBOT_CONFLUENCE_SEARCH_SPACE with my space key

[Wed Jun 10 2015 12:58:19 GMT+0900 (JST)] ERROR SyntaxError: Unexpected token <
  at Object.parse (native)
  at /Users/anirudh.banarji/tp/revrev/node_modules/hubot-confluence/src/hubot-confluence.coffee:52:5, <js>:53:22
  at IncomingMessage.<anonymous> (/Users/anirudh.banarji/tp/revrev/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)

**Comment by amwelch** [comment]
Thanks for letting me know. I will attempt to reproduce this evening.

**Comment by amwelch** [comment]
Sorry, I didn't get a chance to look at this last night, but I'm taking a look now. The problem is that we are not getting valid json back in the response. I'm going to add some better error handling / logging for this failure.

**Comment by amwelch** [comment]
Hi,

It looks like Atlassian started requiring a new flag for authentication. I fixed this and added some better error handling. This fixed the issue for me, but please let me know if you are still having issues.
